kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: golang
  commands:
  - make test
  - make build
- name: publish-docker
  image: plugins/docker
  commands:
  - docker-compose build
  - docker push utain/go-example