kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - make test
  - make build
- name: publish docker
  commands:
  - docker-compose build
  - docker push utain/go-example