version: "3.7"

networks:
  app-network:
services:
  go-example:
    build: .
    container_name: go-server
    image: docker.pkg.github.com/utain/go-12factor-example/go-server:latest
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - app-network