name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Docker Login
      run: docker login docker.pkg.github.com --username ${{secrets.GITHUB_ACTOR}} --password ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker
      run: docker build -t docker.pkg.github.com/utain/go-12factor-example/go-server:latest .
    - name: Push docker image to github
      run: docker push docker.pkg.github.com/utain/go-12factor-example/go-server:latest
    - name: Push docker image to github with tag name
      run: docker tag docker.pkg.github.com/utain/go-12factor-example/go-server:latest docker.pkg.github.com/utain/go-12factor-example/go-server:$(git describe --all)
